name: using_chat_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.1.3
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  http: ^1.2.2
  json_annotation: ^4.8.1
  redis: ^4.0.0
  shared_preferences: ^2.3.2
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^3.0.1
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.8
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
