name: using_chat_api
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  envied: ^1.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.3
  go_router: ^14.0.2
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.8.1
  path_provider: ^2.1.5
  redis: ^4.0.0
  shared_preferences: ^2.3.2
  socket_io_client: ^3.1.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
